#!/bin/bash -l
#insert use commands here
#  $1 is the task file

# input the $SGE_TASK_IDth line of this file into $id
export id=`awk "NR==$SGE_TASK_ID" $1`
#split id on whitespace into array that can be accessed like ${splitID[0]}
#splitID=($id)
#export id=${splitID[0]}
echo  $SGE_TASK_ID : $id
#redirect stdout and stderr to file
export logDir=""
exec 1>>$logDir/$id.olog
exec 2>&1
set -e


if [ ! -e $logDir/$id.done ]
then
	echo Job $JOB_ID:$SGE_TASK_ID started on $HOST: `date`
	#PLACE COMMANDS HERE

	touch $logDir/$id.done
	echo Job finished: `date`
else
	echo Job already done. To redo, rm $logDir/$id.done
fi
